"""Write-time validation for the pgvector cache.

Runs at cache MISS time, *after* the warehouse has executed Genie's SQL but
*before* persisting `(question embedding → SQL)`. Decides whether the freshly-
produced SQL+result is a quality answer worth re-serving on future hits.

Today's only sibling — `cache_validator.py` — runs at cache HIT time and only
compares question text. It can't catch "right question, but the cached SQL was
wrong from day one" — which is what produces the Q111/Q116 wrong-bind failures
documented in eval/RCA_WRONG_BIND_2026-04-27.md and HAIKU_CATALOG_V3.

This module is heuristic-only and deterministic. No LLM call, no extra latency
on cache miss beyond a regex pass. It's the cheapest possible defense against
poisoning the cache with empty results, refusal text, metric-view SQL the
warehouse can't re-execute, and column shapes that don't answer the question.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from typing import Optional, Sequence

from app.services.column_match import fuzzy_column_match

logger = logging.getLogger(__name__)


# Regex matching common Genie refusal / uncertainty patterns. Conservative —
# we only skip the cache write when Genie *explicitly* hedges; benign summary
# text is left alone. Built-in `re.I` plus a single compiled regex.
_REFUSAL_RE = re.compile(
    r"\b("
    r"i\s*(?:can'?t|cannot|wasn'?t able|am unable|don'?t (?:have|know))"
    r"|(?:i'?m|i am)\s*(?:sorry|not sure|unsure)"
    r"|not enough\s*(?:data|info|information|context)"
    r"|couldn'?t\s*(?:find|locate|identify)"
    r"|no\s*(?:data|results|rows|records)\s*(?:matching|for|found|available)"
    r"|metric[s]?\s*[\w \-]*\s*(?:is|are|isn'?t|aren'?t|not)\s*defined"
    r"|no\s*(?:matching|relevant|suitable)\s*(?:metric|column|table|field)"
    r"|unable to (?:answer|respond|generate|produce)"
    r"|outside (?:my|the)\s*(?:scope|knowledge|capabilities)"
    r")\b",
    re.IGNORECASE,
)


# Metric-view SQL is generated by Genie when a Genie Space is built on top of
# a Unity Catalog metric view. The MEASURE() / DIMENSION() functions only
# resolve inside Genie's own execution context — the gateway's cache-hit
# re-exec posts to /api/2.0/sql/statements which does NOT understand them.
# Caching this SQL is a guaranteed Q115-style "cache hit returns FAILED"
# follow-up.
_METRIC_VIEW_RE = re.compile(r"\b(MEASURE|DIMENSION)\s*\(", re.IGNORECASE)


# Patterns the user uses when asking a sub-question that pins down a
# *specific* output column, e.g. "List ONLY the donor_id" or "return just
# trust_fund_name". These map to selector-emitted bind keys — when Genie
# returns SQL that doesn't surface that column, downstream binding fails
# silently with `no_data_array`.
_REQUESTED_COLUMN_RE = re.compile(
    r"(?:list|return|give me|show)\s+"
    r"(?:only(?:\s+the)?|just(?:\s+the)?|the)\s+"
    # Allow `,` and `&` in the capture so compound lists like
    # "donor_id, project_id, region" are captured whole and split later.
    r"([A-Za-z][A-Za-z0-9_ ,&]{0,80})"
    r"(?:\s+(?:column|field|values?))?\b",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class WriteDecision:
    """Result of the validator. `should_write=False` means do NOT cache."""
    should_write: bool
    reason: Optional[str] = None  # "empty_result", "genie_refusal", "metric_view_sql", "column_mismatch"
    detail: Optional[str] = None  # human-readable specifics for logs


def _extract_requested_target(question: str) -> Optional[str]:
    """Extract the column phrase the user asked for if the question follows a
    "list only the X" / "return just Y" pattern. May contain multiple columns
    joined by "and" / "," / "&" — see `_split_targets` to break them apart.
    Returns None for free-form questions where we can't pin down a target.
    """
    if not isinstance(question, str):
        return None
    m = _REQUESTED_COLUMN_RE.search(question)
    if not m:
        return None
    target = m.group(1).strip()
    # Strip trailing filler / qualifiers a user might add.
    target = re.sub(r"\s+(for|in|of|by|from|with|that|which)\b.*$", "", target, flags=re.I).strip()
    # Strip trailing "column" / "field" / "values" — the optional regex group
    # gets eaten by the greedy capture, so peel it off here.
    target = re.sub(r"\s+(column|field|values?)\s*$", "", target, flags=re.I).strip()
    return target or None


# Split on whitespace-bounded `and` / `or` / `plus`, on `,`, and on `&` (with
# optional surrounding whitespace). Bounded matches mean `command_id` and
# `random_value` are NOT split on their internal "and"/"or" substrings.
_TARGET_SPLIT_RE = re.compile(
    r"\s*(?:,|&|\s(?:and|or|plus)\s)\s*",
    re.IGNORECASE,
)


def _split_targets(target_phrase: str) -> list[str]:
    """Break a captured target phrase into individual column candidates.

    `"trust_fund_id and primary_theme"` → `["trust_fund_id", "primary_theme"]`
    `"donor_id, project_id, region"`    → `["donor_id", "project_id", "region"]`
    `"command_id"`                      → `["command_id"]` (no embedded split)
    """
    if not isinstance(target_phrase, str) or not target_phrase.strip():
        return []
    parts = [p.strip() for p in _TARGET_SPLIT_RE.split(target_phrase)]
    return [p for p in parts if p]


def evaluate_cache_write(
    *,
    question: str,
    sql_query: str,
    row_count: Optional[int],
    columns: Optional[Sequence[str]],
    genie_text: Optional[str] = None,
    enabled: bool = True,
) -> WriteDecision:
    """Decide whether to persist a fresh `(question, SQL)` pair into the cache.

    Heuristics, in order. The first SKIP signal wins:
      1. row_count == 0  → empty_result
      2. genie_text matches refusal / uncertainty patterns → genie_refusal
      3. SQL contains MEASURE(/DIMENSION( → metric_view_sql
      4. question explicitly requests a target column not present in result → column_mismatch

    When `enabled` is False, always returns should_write=True (no-op).
    Failure to evaluate (unexpected types, exceptions) fails OPEN — i.e. allows
    the write — so a buggy validator never silently breaks caching.
    """
    if not enabled:
        return WriteDecision(should_write=True)

    try:
        # 1. Empty result
        if row_count is not None and row_count == 0:
            return WriteDecision(
                should_write=False,
                reason="empty_result",
                detail="warehouse returned 0 rows",
            )

        # 2. Genie refusal text
        if genie_text and _REFUSAL_RE.search(genie_text):
            snippet = genie_text.strip().splitlines()[0][:160]
            return WriteDecision(
                should_write=False,
                reason="genie_refusal",
                detail=f"genie_text matched refusal pattern: {snippet!r}",
            )

        # 3. Metric-view SQL — warehouse re-exec will fail on cache hit (Q115 RCA)
        if isinstance(sql_query, str) and _METRIC_VIEW_RE.search(sql_query):
            return WriteDecision(
                should_write=False,
                reason="metric_view_sql",
                detail="SQL contains MEASURE()/DIMENSION() — not standalone-executable",
            )

        # 4. Output columns vs the user's requested target(s).
        # Compound targets ("X and Y", "X, Y, Z") get split — we accept the
        # write if AT LEAST ONE sub-target matches a result column, so that
        # questions like "List ONLY the trust_fund_id and primary_theme" pass
        # whenever those columns are present (independently or together).
        target_phrase = _extract_requested_target(question)
        if target_phrase and columns:
            col_list = [c for c in columns if isinstance(c, str)]
            sub_targets = _split_targets(target_phrase)
            if col_list and sub_targets and not any(
                fuzzy_column_match(t, col_list) is not None for t in sub_targets
            ):
                return WriteDecision(
                    should_write=False,
                    reason="column_mismatch",
                    detail=f"question asked for {sub_targets!r}, result columns were {col_list}",
                )

        return WriteDecision(should_write=True)

    except Exception as exc:
        # Fail open. A broken heuristic must not silently break caching.
        logger.warning("cache_write_validator failed-open: %s", exc, exc_info=True)
        return WriteDecision(should_write=True)
