#!/usr/bin/env bash
# Pre-deploy build: frontend bundle + git version injection.
# Used by `make build` (called from `make deploy`) before `databricks bundle deploy`.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# 1. Frontend
if [ ! -d frontend/node_modules ]; then
    echo "==> npm install"
    (cd frontend && npm install)
fi
echo "==> npm run build"
(cd frontend && npm run build)

# 2. Inject git version into backend/app/_version.py (gitignored).
# version.py prefers this file; falls back to live git describe in dev.
VERSION="$(git describe --tags --always --dirty 2>/dev/null || echo dev)"
cat > backend/app/_version.py <<EOF
# Auto-generated by scripts/build.sh — do not edit.
__version__ = "${VERSION}"
EOF
echo "==> wrote backend/app/_version.py: ${VERSION}"
